### ISSUE TITLE
Crashes when I try to generate patches

### ISSUE THREAD

**Issue by RC-jimmanson** [jermdavis/PatchMaker#21]
I have PatchMaker 1.3. I loaded the Sitecore.config file and created patches for the upload folder, the temp folder, and the data folder. When I click on "File" menu and select to "Generate Patches" the app crashes
![Capture](https://user-images.githubusercontent.com/47363020/80508170-5036cb00-893d-11ea-8b91-b6639f319663.PNG)

**Comment by RC-jimmanson** [comment]
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
PatchMaker.PatchException: PatchAttribute failed: The xpath query '/sitecore[@database='SqlServer' and @role='http://www.sitecore.net/xmlconfig/role/' and @security='http://www.sitecore.net/xmlconfig/security/']/sc.variable[@name='mediaFolder' and @value='/upload']' matched no nodes in the source document.
Parameter name: XPathForElement
   at PatchMaker.BaseAttributeChange.ApplyPatchElement(XDocument sourceXml, XDocument patchXml) in C:\Users\jeremy\source\repos\PatchMaker\PatchMaker\BaseAttributeChange.cs:line 43
   at PatchMaker.PatchGenerator.GeneratePatchFile(IEnumerable`1 patches) in C:\Users\jeremy\source\repos\PatchMaker\PatchMaker\PatchGenerator.cs:line 31
   at PatchMaker.App.PatchGenerationForm..ctor(ListBox patchListView, XDocument sourceXml, String sourceFileName) in C:\Users\jeremy\source\repos\PatchMaker\PatchMaker.App\PatchGenerationForm.cs:line 38
   at PatchMaker.App.PatchPlanningForm.generatePatchesToolStripMenuItem_Click(Object sender, EventArgs e) in C:\Users\jeremy\source\repos\PatchMaker\PatchMaker.App\PatchPlanningForm.cs:line 120
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4150.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
PatchMaker.App
    Assembly Version: 1.3.0.0
    Win32 Version: 1.3.0.0
    CodeBase: file:///C:/Users/jmanson/Downloads/PatchMaker-v1.3/PatchMaker.App.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4150.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4001.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4121.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
PatchMaker
    Assembly Version: 1.3.0.0
    Win32 Version: 1.3.0.0
    CodeBase: file:///C:/Users/jmanson/Downloads/PatchMaker-v1.3/PatchMaker.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by jermdavis** [comment]
While you closed this yourself @RC-jimmanson, it was a valid bug. Looking into it has caused me to add a couple of fixes for v1.4, which (if I got it right) should prevent the crash you saw?

**Comment by RC-jimmanson** [comment]
Sorry, I had a few issues posting. Thanks for looking at it anyway. This will be an awesome tool!
